sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
before_install:
- "$BASE_DIR/deploy/prepare_ci.sh"
after_success:
- "$BASE_DIR/deploy/after_success.sh"
install:
- "$BASE_DIR/deploy/ci.sh"
notifications:
  email: false
env:
  matrix:
  - JAVA_VERSION=openjdk8
  - JAVA_VERSION=openjdk9
  global:
  - BASE_DIR="`pwd`"
cache:
  directories:
  - "$HOME/.m2"