sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
before_install:
- "$BASE_DIR/deploy/prepare_ci.sh"
after_success:
- "$BASE_DIR/deploy/ci.sh"
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
env:
  global:
  - BASE_DIR="`pwd`"
cache:
  directories:
  - "$HOME/.m2"